{"name": "test", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '.\\\\data.yaml'", "trace": "self = <codejiang.testcodejiang.Test object at 0x000002AB27269948>\n\n    def test(self):\n        main = Main()\n>       main.goto_shouye()\n\ntestcodejiang.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nmain.py:24: in goto_shouye\n    self.find(By.XPATH, '//*[@id=\"app\"]/section/div/main/div/form/div[1]/div/div[1]/input').send_keys(Datas.data(self)[0])\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <codejiang.main.Main object at 0x000002AB27276688>\n\n    def data(self):\n        list =[]\n>       t = yaml.safe_load(open(\".\\\\data.yaml\"))\nE       FileNotFoundError: [Errno 2] No such file or directory: '.\\\\data.yaml'\n\ncommon\\data.py:7: FileNotFoundError"}, "start": 1611974304807, "stop": 1611974325217, "uuid": "d634fdc5-0ccd-42a8-81c2-a4fc85dcd026", "historyId": "5f969d9c4523f7b324fae792572ee388", "testCaseId": "8db55232ce9ffec55c5cb34d4901daf6", "fullName": "testcodejiang.Test#test", "labels": [{"name": "suite", "value": "testcodejiang"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "DESKTOP-E48KJ25"}, {"name": "thread", "value": "7680-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcodejiang"}]}