{"name": "test", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'codejiang/common/data.yaml'", "trace": "self = <codejiang.testcodejiang.Test object at 0x000002B4E97F9808>\n\n    def test(self):\n        main = Main()\n>       main.goto_shouye()\n\ntestcodejiang.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nmain.py:24: in goto_shouye\n    self.find(By.XPATH, '//*[@id=\"app\"]/section/div/main/div/form/div[1]/div/div[1]/input').send_keys(Datas.data(self)[0])\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <codejiang.main.Main object at 0x000002B4E9804308>\n\n    def data(self):\n        list =[]\n>       t = yaml.safe_load(open(\"codejiang/common/data.yaml\"))\nE       FileNotFoundError: [Errno 2] No such file or directory: 'codejiang/common/data.yaml'\n\ncommon\\data.py:7: FileNotFoundError"}, "start": 1611974189365, "stop": 1611974209527, "uuid": "d5a7b6e2-a434-4a0e-a5af-2f05a58e201f", "historyId": "5f969d9c4523f7b324fae792572ee388", "testCaseId": "8db55232ce9ffec55c5cb34d4901daf6", "fullName": "testcodejiang.Test#test", "labels": [{"name": "suite", "value": "testcodejiang"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "DESKTOP-E48KJ25"}, {"name": "thread", "value": "4456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcodejiang"}]}