{"name": "test", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'data.yaml'", "trace": "self = <codejiang.testcodejiang.Test object at 0x000001A82D9D79C8>\n\n    def test(self):\n        main = Main()\n>       main.goto_shouye()\n\ntestcodejiang.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nmain.py:24: in goto_shouye\n    self.find(By.XPATH, '//*[@id=\"app\"]/section/div/main/div/form/div[1]/div/div[1]/input').send_keys(Datas.data(self)[0])\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <codejiang.main.Main object at 0x000001A82D9E6688>\n\n    def data(self):\n        list =[]\n>       t = yaml.safe_load(open(\"data.yaml\"))\nE       FileNotFoundError: [Errno 2] No such file or directory: 'data.yaml'\n\ncommon\\data.py:7: FileNotFoundError"}, "start": 1611973650624, "stop": 1611973670609, "uuid": "0620f6ca-802b-43f2-a5b6-9e53154ea235", "historyId": "5f969d9c4523f7b324fae792572ee388", "testCaseId": "8db55232ce9ffec55c5cb34d4901daf6", "fullName": "testcodejiang.Test#test", "labels": [{"name": "suite", "value": "testcodejiang"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "DESKTOP-E48KJ25"}, {"name": "thread", "value": "16316-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcodejiang"}]}